apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: akhq
  labels:
    app: akhq
spec:
  serviceName: akhq-headless
  replicas: 1
  selector:
    matchLabels:
      app: akhq
  template:
    metadata:
      labels:
        app: akhq
    spec:
      containers:
        - name: akhq
          image: tchiotludo/akhq:latest
          ports:
            - containerPort: 8080
          env:
            - name: AKHQ_CONFIGURATION
              value: |
                akhq:
                  server:
                    servlet:
                      context-path: /
                  connections:
                    kafka-cluster:
                      properties:
                        bootstrap.servers: "kafka-headless:9092"

