apiVersion: v1
kind: Service
metadata:
  name: akhq-headless
  labels:
    app: akhq
spec:
  clusterIP: None
  selector:
    app: akhq
  ports:
    - name: http
      port: 8080
      targetPort: 8080

