apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"kafka","namespace":"default"},"spec":{"clusterIP":"None","ports":[{"port":9092}],"selector":{"app":"kafka"}}}
  creationTimestamp: "2025-06-10T08:02:06Z"
  name: kafka
  namespace: default
  resourceVersion: "695"
  uid: 0ad37c25-0cea-442f-91d2-b4e485e4d706
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: kafka
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
