apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka-headless
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      initContainers:
        - name: wait-for-zookeeper
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              for i in 0 1 2; do
                echo "Waiting for zookeeper-${i}.zookeeper-headless:2181..."
                until nc -z zookeeper-${i}.zookeeper-headless 2181; do
                  echo "Still waiting for zookeeper-${i}..."
                  sleep 2
                done
              done
              echo "All ZooKeeper nodes are reachable!"
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.6.0
          ports:
            - containerPort: 9092
              name: internal
            - containerPort: 9093
              name: external
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_HEAP_OPTS
              value: "-Xmx512m -Xms512m"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-0.zookeeper-headless:2181,zookeeper-1.zookeeper-headless:2181,zookeeper-2.zookeeper-headless:2181"
            - name: NODE_IP
              value: "127.0.0.1" # 🧠 IP of your WSL Node (check: `kubectl get nodes -o wide`)
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
          command:
            - sh
            - -c
            - |
              export KAFKA_BROKER_ID=$(echo ${POD_NAME} | awk -F'-' '{print $NF}')
              export NODE_PORT=$((30092 + ${KAFKA_BROKER_ID}))
              #export KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://${POD_NAME}.kafka-headless.default.svc.cluster.local:9092,EXTERNAL://${NODE_IP}:${NODE_PORT}"
              # Put EXTERNAL first for client compatibility
              export KAFKA_ADVERTISED_LISTENERS="EXTERNAL://${NODE_IP}:${NODE_PORT},PLAINTEXT://${POD_NAME}.kafka-headless.default.svc.cluster.local:9092"
              #export KAFKA_ADVERTISED_LISTENERS="EXTERNAL://${NODE_IP}:${NODE_PORT}"
              echo "KAFKA_ADVERTISED_LISTENERS=$KAFKA_ADVERTISED_LISTENERS"
              exec /etc/confluent/docker/run
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi

