apiVersion: v1
kind: Service
metadata:
  name: kafka-1-nodeport
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: kafka-1
  ports:
    - name: kafka
      port: 9093
      targetPort: 9093
      nodePort: 30093
